export const canonicalExerciseNames = [
  "Alternating Dumbbell Curl",
  "Archer push up",
  "Backward lunges",
  "Barbell Ab Rollout",
  "Barbell Ab Rollout - On Knees",
  "Barbell Back Squat",
  "Barbell calf raises",
  "Barbell Curl 21s",
  "Barbell Curls",
  "Barbell Deadlift",
  "Barbell Front Raise",
  "Barbell Full Squat",
  "Barbell Glute Bridge",
  "Barbell Good Morning",
  "Barbell Hip Thrust",
  "Barbell Incline Bench Press - Medium Grip",
  "Barbell Lunge",
  "Barbell Rows",
  "Barbell Shoulder Press - Barbell Overhead Press - Barbell Military Press",
  "Barbell Shrug",
  "Barbell Sit-Up",
  "Barbell Sumo Squat",
  "Barbell Sumo Squat",
  "Barbell Thruster - Straight Bar Thruster",
  "Barbell walking lunges",
  "Bear crawl into explosive jumps",
  "Bear crawl shoulder tap to pike push up",
  "Bear crawl to pike push up",
  "Bear crawls",
  "Bear plank ankle taps into jumps",
  "Bear plank shoulder taps",
  "Bear plank shoulder taps - 30",
  "Bear plank side tap sidewalks",
  "Bear plank steps and hops",
  "Bear plank toe taps",
  "Bear toe taps",
  "Behind the Head Curl with Cable",
  "Behind the Neck Rope Pulldown",
  "Behind the Neck Shoulder Press Machine",
  "Bench Jump",
  "Bench Press",
  "Bent leg v-sit into punches",
  "Bent Over Barbell Row",
  "Bent Over Barbell Row Overhand Grip",
  "Bent Over Barbell Row Underhand Grip",
  "Bent over Dumbbell Rear Delt Raise",
  "Bent Over Dumbbell Reverse Fly",
  "Bent over Dumbbell Tricep extension",
  "Bent Over One-Arm Long Bar Row",
  "Bent Over Two-Arm Long Bar Row - 105",
  "Bent Over Two-Dumbbell Row with Palms In",
  "Bicycle punches",
  "Boat hold",
  "Boat pose",
  "Bodyweight Squat (air squat)",
  "Bodyweight Triceps Extension (with bar)",
  "Bow pose",
  "Bridge pose",
  "Broad jumps",
  "Bulgarian split squat",
  "Bulgarian split squat - with Barbell",
  "Bulgarian split squat with Dumbbell",
  "Burpee",
  "Burpee (No jump)",
  "Burpee (No jump) into high plank with shoulder tabs",
  "Butt bridges",
  "Butt kickers",
  "Butterfly crunches",
  "Butterfly Jumps",
  "Butterfly Stretch",
  "C+A75able Deadlift",
  "Cable Front Kick",
  "Cable Front Raise",
  "Cable Glute Kickback",
  "Cable Hip Abduction",
  "Cable Hip Extension",
  "Cable Kickback",
  "Cable Lateral Raise",
  "cable Preacher Curl",
  "Cable Rear Delt Fly",
  "Cable Rope Face Pull",
  "Cable Rope Pullover",
  "Cable Rope Tricep Pushdown",
  "Cable Straight Leg Kickback",
  "Cable Tricep Pushdown",
  "Calf gas peddlers",
  "Calf stretch (right)",
  "Calf stretch (left)",
  "Calf stretch (right)",
  "Camel pose",
  "Cat cow pose",
  "Cat pose",
  "Chair pose",
  "Chair sit ups",
  "Chameleon push up",
  "Chameleon push up to mountain climbers",
  "Chest and shoulder",
  "Child's pose - Lower back",
  "Child's pose",
  "Close Grip Bench Barbell",
  "Close Grip Dumbbell Press",
  "Close Grip Incline Dumbbell Press",
  "Close Grip Plate Press",
  "Close Grip Lat Pulldown",
  "Close Grip Lat Pulldown to Waist",
  "Close Grip Plate Press",
  "Cobblers pose",
  "Cobra pose",
  "Cobra pose",
  "Concentration Curl",
  "Concentration Hammer Curl",
  "Corpse pose",
  "cote Badpmg",
  "Cow face pose (left)",
  "Cow face pose (right)",
  "Cow pose",
  "Crab hold to to taps",
  "Crab hold toe taps",
  "Crab walk to squat",
  "Crab walks into squats",
  "Crescent lunge (left)",
  "Crescent lunge (right)",
  "Criss-cross jumping jacks",
  "Cross Body Hammer Curl",
  "Cross body pulls to hamstring kicks",
  "Crunches",
  "Cuban Press",
  "Deadlift with Kettlebell",
  "Deadstop push up",
  "Deadstop push up into Superman crunches",
  "Deadstop push ups",
  "Deadstop pushup to superman crunch",
  "Decline Close Grip Dumbbell Press",
  "Declined Push up - 56",
  "Devil press",
  "Dips",
  "Dips - Triceps Version",
  "Dips on bench",
  "Dive bombers",
  "Donkey kick with Dumbbell",
  "Downward dog",
  "Downward facing dog split (left)",
  "Downward facing dog split (right)",
  "Drop dead push up into knee in",
  "Dumbbel calf raises",
  "Dumbbell Bench Press",
  "Dumbbell Bicep Curl Standing",
  "Dumbbell deadlift",
  "Dumbbell deltoid fly",
  "Dumbbell Discus",
  "Dumbbell Discus (L)",
  "Dumbbell double snatch",
  "Dumbbell External Rotation",
  "Dumbbell floor chest press",
  "Dumbbell fly",
  "Dumbbell forward lunge",
  "Dumbbell get ups ®",
  "Dumbbell glute bridge",
  "Dumbbell Lunges",
  "Dumbbell Lying Rear Lateral Raise",
  "Dumbbell Lying Rear Lateral Raise - One arm",
  "Dumbbell One-Arm Shoulder Press (L)",
  "Dumbbell One-Arm Shoulder Press (R)",
  "Dumbbell One-Arm Upright Row (L)",
  "Dumbbell One-Arm Upright Row ®",
  "Dumbbell pistol squats",
  "Dumbbell plank row",
  "Dumbbell Rear Lunge+A174",
  "Dumbbell Scaption",
  "Dumbbell Scissors",
  "Dumbbell shadow box",
  "Dumbbell Shoulder Press",
  "Dumbbell shoulder punches",
  "Dumbbell Shrug",
  "Dumbbell Side Bend (L)",
  "Dumbbell side Bend (R)",
  "Dumbbell Side lunge",
  "Dumbbell Side lunge (L)",
  "Dumbbell Single leg deadlift",
  "Dumbbell Squat",
  "Dumbbell Thruster",
  "Dumbbell upper cuts",
  "Dumbbell waiter curls",
  "Dumbbell wrist curls",
  "Elbow to knee plank",
  "Elevated push up",
  "Explosive jump squats",
  "Explosive knee drive",
  "Explosive push",
  "Explosive push ups",
  "Explosive side to side push up",
  "Explosive sprinter Lunge (left)",
  "Explosive sprinter Lunge (right)",
  "Extended side angle pose (left)",
  "Extended side angle pose (right)",
  "Farmers walk",
  "Figure Four Stretch (L)",
  "Figure Four Stretch (R)",
  "Fire log pose (left)",
  "Fire log pose (right)",
  "Flat Cable Fly",
  "Floor Press",
  "Flutter kicks",
  "Forward and backward lunge",
  "Forward lunge with lateral flexion",
  "Forward to Reverse Bear Crawl",
  "Frog pose",
  "Frog stretch",
  "Froggers",
  "Front Barbell Squat",
  "Front Two-Dumbbell Raise",
  "Full range push ups",
  "Garland pose",
  "Gate pose (left)",
  "Gate pose (right)",
  "Get ups (no jump)",
  "Get ups with Jump",
  "Glute bridge",
  "Goblet squat",
  "Goblet Squat with Kettlebell",
  "Goddess pose",
  "Good Mornings",
  "Good Mornings with barbell",
  "Hack Squat",
  "Hack Squat Wide Stance",
  "Half boat pose",
  "Half frog pose (left)",
  "Half frog pose (right)",
  "Half lord of the fishes pose (left)",
  "Half lord of the fishes pose (right)",
  "Half moon (left)",
  "Half moon (right)",
  "Half split (left)",
  "Half split (right)",
  "Half squat get up",
  "Halo with dumbbell (L)",
  "Halo with dumbbell (R)",
  "Hammer Curls",
  "Hang clean",
  "Hang Snatch",
  "Happy baby pose",
  "Heel to toe walk",
  "Heel touches",
  "Heels to Butt",
  "High Cable Curl",
  "High Cable Fly",
  "High knees",
  "High plank alternating single leg knee tuck",
  "High plank to low plank",
  "High plank to side plank",
  "High plank toe touches",
  "High Row Machine",
  "High toe touches",
  "Hip Abduction Machine",
  "Hip circle hops",
  "Hip stretch (left)",
  "Hip stretch (right)",
  "Hollow body skullcrushers",
  "Horizontal leg Press",
  "In and out Shoulder tap push ups",
  "Inchworm",
  "Inchworm to pike push ups",
  "Inchworms to push ups to pike push up",
  "Incline Barbell Front Raise",
  "Incline Barbell Press",
  "Incline Cable Fly",
  "Incline Dumbbell Crossover",
  "Incline Dumbbell Curl",
  "Incline Dumbbell Lateral Raise",
  "Incline Dumbbell Press",
  "Incline Dumbbell Rear Delt Raise",
  "Incline Dumbbell Reverse Fly",
  "Incline Dumbbell Row",
  "Incline Machine Press",
  "Incline Machine Shoulder Press",
  "Inclined diamond push up",
  "Inclined push up",
  "Inclined wide push up",
  "Jump get ups",
  "Jump knee tucks",
  "Jump squat to backward lunge",
  "Jump squats",
  "Jump Squats - Squat Jumps",
  "Jumping jacks",
  "Jumping lunges",
  "Jumping Rope skips",
  "Kettlebell swing",
  "Kettlebell Thruster",
  "Kettlebell Turkish Get-Up (Lunge style)",
  "Knee pseudo pushups",
  "Knee push ups",
  "Knee raise marches",
  "Knee raises",
  "Knee raises (Hanging)",
  "Knee to Chest Stretch (L)",
  "Knee to Chest Stretch (R)",
  "Knee tucked Side plank up and downs (Left)",
  "Knee tucked Side plank up and downs (Right)",
  "Kneeling jump squat",
  "L dumbbell raises",
  "L-sit hold (dip bar or paralettes)",
  "L-sit to tucked L-sit",
  "Lat Pulldown",
  "Lateral neck stretch (left)",
  "Lateral neck stretch (right)",
  "Laying leg raises to windshield wipers",
  "Leg Extension",
  "Leg Press",
  "Leg Raises",
  "Lotus pose",
  "Low Cable Crossover",
  "Low Cable Curl V-Bar",
  "Low Cable Rope Curl",
  "Low lunge (left)",
  "Low lunge (right)",
  "Lunge matrix",
  "Lunge With Spinal Twist",
  "Lunges body weight",
  "Lying Barbell Front Raise",
  "Lying Barbell Skull Crusher",
  "Lying Dumbbell Skull Crusher",
  "Lying Dumbbell Tricep Extension",
  "Lying elbow to knee crunch",
  "Lying EZ Bar Curl",
  "Lying knee tucks",
  "Lying leg curl",
  "Lying leg raises with crunch",
  "Lying oblique crunch",
  "Lying Overhead Triceps Extension",
  "Lying toe reaches",
  "Machine Bicep Curl",
  "Machine Chest Fly",
  "Machine Glute Kickback",
  "Machine Lateral Raise",
  "Machine Reverse Fly",
  "Machine Shoulder Press",
  "Mid Row Machine",
  "Mountain Climbers",
  "Mountain climbers into shoulder taps",
  "Mountain pose",
  "My Side Bend Stretch (L)",
  "Negative pull ups",
  "Neutral Grip Lat Pulldown",
  "Normal grip pull ups (Full range of motion)",
  "Oblique Crunches",
  "One-Arm Dumbbell Row bench",
  "One-Arm Kettlebell Military Press",
  "One-Arm Kettlebell Snatch - From ground",
  "One-Arm Kettlebell Snatch from ground",
  "One-Arm Side Laterals (L)",
  "One-Arm Side Laterals (R)",
  "Open and close jumping jacks",
  "Over and under",
  "Overhead Cable Rope Extension",
  "Overhead Lunge",
  "Overhead Squat",
  "Pec Deck Fly",
  "Pike hold knee bends",
  "Pike push ups",
  "Plank",
  "Plate Front Raise",
  "Plie Dumbbell Squat",
  "Plow pose",
  "Plyo Push-Up",
  "Posterior upper arm stretch (left)",
  "Posterior upper arm stretch (right)",
  "Power Snatch",
  "Preacher Curl",
  "Puppy pose",
  "Push ups",
  "Pyramid pose (left)",
  "Pyramid pose (right)",
  "Rack Pulls",
  "Reclined butterfly",
  "Reclined pigeon pose (left)",
  "Reclined pigeon pose (right)",
  "Reclined windshield wipers",
  "Reverse Cable Preacher Curl",
  "Reverse fly plank to plank hop",
  "Reverse grip bent over rows",
  "Reverse Grip Skull Crusher",
  "Reverse Lunge into Knee Drive",
  "Reverse lunge to knee drive",
  "Reverse Preacher Curl",
  "Reverse warrior (left)",
  "Reverse warrior (right)",
  "Revolved chair pose (left)",
  "Revolved chair pose (right)",
  "Revolved triangle pose (left)",
  "Revolved triangle pose (right)",
  "Rocking horse push up into explosive jump",
  "Romanian Deadlift",
  "Run in place",
  "Russian twists",
  "Sage marichi I pose (left)",
  "Sage marichi I pose (right)",
  "Scapula hold",
  "Seated Barbell Military Press",
  "Seated Cable Fly",
  "Seated Cable Row Close Neutral Grip",
  "Seated Cable Row Neutral Grip",
  "Seated Cable Row Underhand Grip",
  "Seated Cable Row Wide Grip",
  "Seated Calf Raises",
  "Seated Dumbbell Curl",
  "Seated Dumbbell Triceps Extension",
  "Seated eagle arm (right)",
  "Seated eagle arms (left)",
  "Seated EZ Bar Curl",
  "Seated flutter kicks",
  "Seated forward bend",
  "Seated Hammer Curl",
  "Seated High Row Machine",
  "Seated Hip Abduction Machine",
  "Seated Incline Press with Machine",
  "Seated Leg Curl",
  "Seated leg raises",
  "Seated Low Cable Curl",
  "Seated Machine Chest Press",
  "Seated Neutral Grip Cable Press",
  "Seated Neutral Grip Row Machine",
  "Seated shoulder push downs",
  "Seated Shoulder Squeeze",
  "Seated wide angle straddle",
  "Shot Caller Burpee",
  "Shoulder press - Overhead press - Military press",
  "Shoulder tap burpees",
  "Shoulder taps",
  "Shoulder taps into ankle taps",
  "Side bend (ieft)",
  "Side bend (right)",
  "Side Bend Stretch (R)",
  "Side hurdel jumps to mountain climbers",
  "Side jump skaters",
  "Side Lateral Raise with Dumbbells",
  "Side plank pose (left)",
  "Side plank pose (right)",
  "Side plank pulses",
  "Side plank pulses (Right side)",
  "Side plank up and down (left)",
  "Side plank up and down (right)",
  "Side to side plank walk",
  "Side to side plank walk into shoulder taps",
  "Side to side push up",
  "Side to side squat",
  "Sideplank",
  "Sit ups",
  "Slingshot into T-Spine rotation",
  "Smith Machine Behind the Neck Press",
  "Smith Machine Bent Over Row Overhand Grip",
  "Smith Machine Bent Over Row Underhand Grip",
  "Smith Machine Deadlift",
  "Smith Machine Glute Squat",
  "Smith Machine Good Morning",
  "smith Machine Hip Thrust",
  "Smith Machine Incline Press",
  "Smith Machine Lunge",
  "Smith Machine Squat",
  "Smith Machine Step-Ups",
  "Smith Machine Sumo Squat",
  "Smith Machine Upright Row",
  "Sphinx pose",
  "Spider Curl",
  "Spiderman push up",
  "split squat (L)",
  "Split squat (R)",
  "Sprinter Butt bridges",
  "Squat taps into jump squats",
  "Squat thruster",
  "Squat to alternating toe taps",
  "Squat to Cable Row",
  "Squat to toe taps",
  "Squats into fly jacks",
  "Squats to knee",
  "Standing Cable Fly",
  "Standing Dumbbell Straight-Arm Front Delt",
  "Standing Dumbbell Triceps Extension",
  "Standing EZ Bar Curl",
  "Standing forward bend",
  "Standing Hamstring stretch (L)",
  "Standing Hamstring Stretch (R)",
  "Standing High Cable Row",
  "Standing Inner-Biceps Curl",
  "Standing knee thrusts",
  "Standing Inner-Biceps Curl",
  "Standing Low Cable Row",
  "Standing Neutral Grip Cable Press",
  "Standing One-Arm DB Triceps Extension (L)",
  "Standing One-Arm DB Triceps Extension (R)",
  "Standing Palm-In One-Arm Dumbbell Press (L)",
  "Standing Palm-In One-Arm Dumbbell Press (R)",
  "Standing Quad Stretch (L)",
  "Standing Quad Stretch (R)",
  "Standing Reverse Curl",
  "Standing Single Leg Curl",
  "Star crunch into Half V-ups",
  "Star Jump Burpees",
  "Static Lunge on Machine",
  "Sumo walk",
  "Superman crunches",
  "Superman extensions",
  "Supported shoulder stand",
  "T press up",
  "T-Bar Row",
  "Tiger pose (left)",
  "Tiger pose (right)",
  "Toe Touchers",
  "Toes to bar",
  "Tree pose (left)",
  "Tree pose (right)",
  "Triangle pose (left)",
  "Triangle pose (right)",
  "Tricep extension knee ins",
  "Tucked L-sit hold (Hanging)",
  "Underhand Grip Cable Pushdown",
  "Underhand Lat Pulldown",
  "Upper back and shoulder stretch (left)",
  "Upper back and shoulder stretch (right)",
  "Upright Barbell Row",
  "Upward facing dog pose",
  "Walking knee raises",
  "Walking lunges",
  "Warrior I (left)",
  "Warrior I (right)",
  "Warrior II (left)",
  "Warrior II (right)",
  "Warrior III (left)",
  "Warrior III (right)",
  "Wheel pose",
  "Wide Grip Barbell Curl",
  "Wide Grip Lat Pulldown",
  "Wide Grip Smith Machine Upright Row",
  "Wild thing pose (left)",
  "Wild thing pose (right)",
  "Y-superman crunch",
  "Zercher Squats",
] as const;

export type CanonicalExerciseName = (typeof canonicalExerciseNames)[number];
